### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by adam-kemeny** [NexZhu/SkillSet#5]
```
npm run build

> skillset@0.1.0 build C:\Users\user\Documents\git\SkillSet
> webpack

C:\Users\user\Documents\git\SkillSet\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\Users\user\Documents\git\SkillSet\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at C:\Users\user\Documents\git\SkillSet\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (C:\Users\user\Documents\git\SkillSet\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\Users\user\Documents\git\SkillSet\node_modules\webpack\bin\webpack.js:156:2)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skillset@0.1.0 build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skillset@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-10-18T11_06_13_592Z-debug.log
```

**Comment by NexZhu** [comment]
Node.js version I used back then has been quite old, I'll update the dependencies.

**Comment by jonatask** [comment]
Resolution here:
https://github.com/NexZhu/SkillSet/pull/6
